services:
    dev:
        build:
            context: .
            args:
                USER: $USER
                USER_ID: $USER_ID
        working_dir: /workspace
        volumes:
            - .:/workspace
        stdin_open: true
        tty: true
